### PR TITLE
Add additional contact icons

### PR DESCRIPTION
**Pull request by alehel**
## Description

Add contact icons for LinkedIn, Gitlab, Weibo, Line and Instagram. Also, add missing code for existing Facebook icon.

## Related Issues

Addresses #371

### CODE REVIEW

**Comment by alehel** [comment]
I've been unable to find a way to link to WeChat profiles. While searching for info I've found several posts stating that its not possible. These posts however were a few years old. So it might have changed. I was however unable to find any info on how to do it.

**Comment by alxshelepenok** [comment]
@alehel 
> Do we want all the icons to show by default, or should we hide the new ones by removing the # in the config.js file?

Great, I think you should display Facebook, Linkedin, Github, Twitter, Telegram, Instagram. All others can be hidden.

**Comment by alehel** [comment]
@alxshelepenok 
>
> Great, I think you should display Facebook, Linkedin, Github, Twitter, Telegram, Instagram. All others can be hidden.

Sounds like good choices. I've made the change 👍

**Comment by alxshelepenok** [comment]
Thanks for your PR, right now i merge it

**Pull request merged**
