### PR TITLE
Move lost and postcss-pxtorem to prod dependencies

### PR DESCRIPTION
**Pull request by namdnguyen**
## Description

Netlify builds fail if `NODE_ENV` is set to "production". Moving the `lost` and `postcss-pxtorem` packages out of the devDependencies list fixes this.

Users can choose to set `NODE_ENV` to "production" in their `netlify.toml` file, which is [set to "development" by default in Netlify](https://www.netlify.com/docs/build-settings/#build-environment-variables). Or they can set it in the Netlify "Deploy Settings" on the site.

### CODE REVIEW

**Comment by namdnguyen** [comment]
The checks probably doesn't check for when `NODE_ENV="production"`. I tested on my fork on Netlify and the build succeeded, but the CI tests might need to be updated to test with both "production" and "development" values of `NODE_ENV`.

**Comment by alxshelepenok** [comment]
@namdnguyen Currently, starter is being built on the Netlify.
If you pass the argument `NODE_ENV="production"`, then all devDependencies for building will not be installed.
So I'm not sure if that makes sense. I think it makes sense if the build occurs on the localhost. Or I'm wrong?

**Comment by namdnguyen** [comment]
Hi @alxshelepenok, I am also using Netlify. I did try to build setting the environment variable `NODE_ENV="production"` in the web console, which failed because it was missing the lost and postcss-torem modules. This pull request is moving those two packages out of devDependencies.

Maybe I am doing something wrong? You could check by building `master` on Netlify.

**Comment by namdnguyen** [comment]
BTW, thank you for the awesome starter template! This is my first time digging into Gatsby, and I've learned a lot already by going through the Lumen code base.

**Comment by alxshelepenok** [comment]
@namdnguyen  Thanks for the feedback ;) 
I tried to build a project with `NODE_ENV="production"` on Netlify and I also got an error, but this is normal behavior, because devDependencies were not installed https://github.com/yarnpkg/yarn/issues/1830

surprisingly, the error related only to lost and postcss-pxtorem (all other devDependencies were most likely installed from Gatsby dependencies or other packages).

In those cases where the installation of dependencies and building the project occurs during deployment, then it is more correct not to use `NODE_ENV="production"` in Netlify.

**Comment by namdnguyen** [comment]
@alxshelepenok I'm not too familiar with lost and postcss-pxtorem. Are those only used during development or testing? If it's needed to build the site, then moving them out of devDependencies will allow for `NODE_ENV="production"` and keep a strict distinction between prod and dev dependencies.

I don't mind continuing to leave off setting `NODE_ENV` in Netlify, but I was hoping to optimize the build process by leaving out the development and testing packages. However, I feel like I'm missing something in understanding the deployment process that you may be pointing to.

**Comment by alxshelepenok** [comment]
Lost and postcss-pxtorem typically belong to development, since they are used by postcss as plugins only during build, and build occurs at deployment time in Netlify.

As an optimization, you can clear node_modules to save disk space like this [#L10](https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/Dockerfile.production#L10) but it does not reduce deployment time.

**Comment by namdnguyen** [comment]
Thanks for the clarification, @alxshelepenok. I'm also new to node and javascript, so I'm still learning how things work. I appreciate the help!

Feel free to close the pull request.

I think I'm starting to understand. Could you confirm whether this is correct? Production environment doesn't really exist for Gatsby because the CDN is serving the static files. I was under the assumption that `yarn build` and `yarn deploy` would be able to build without devDependencies. `yarn develop`, `yarn lint`, `yarn test` need devDependencies packages to complete. Would this be the case for other applications, but not important for Gatsby?

**Comment by alxshelepenok** [comment]
I think this can be attributed to any static site hosted by Netlify.
You cannot use `NODE_ENV = production` when your repo is in sync with Netlify.

For some reason, many people overlook this; deployment to Netlify can be done locally (https://www.netlify.com/docs/cli) (a static site must be generated first):

deploy with netlify

In this case, there is no need to build or install any dependencies. But even here, `NODE_ENV = production` will not affect anything.

**Comment by namdnguyen** [comment]
Wow, I did not know about the Netlify CLI! Thanks for the pointer and for the screen capture!

**Pull request closed without merging**
