### PR TITLE
add linkedin icon to the sidebar

### PR DESCRIPTION
**Pull request by AlexanderThiele**
## Description

Hey! I came across Gatsby and i really like your template!
I added the linkedin Icon to the sidebar. Maybe someone else is also interested in.

I did not discuss this in the issues and also didn't increase the version number since it's just a nice to have update?

Have a nice week!

### CODE REVIEW

**Comment by andrerpena** [comment]
Hey. Thanks for your contribution. You forgot to change get-contact-href so that the value in the config will be properly translated to https://linkedin.com/whatever

**Comment by andrerpena** [comment]
@AlexanderThiele, out of curiosity, how did you get this perfectly fitting SVG? I'm asking because I would like to do the same but for Stackoverflow

**Comment by AlexanderThiele** [comment]
Hi @andrerpena oh yes you're right, the link is missing! will add it soon!

you need to adjust the viewbox (height, width) of the svg to fit the image and and positioning.

thanks for the hint!

**Comment by andrerpena** [comment]
@AlexanderThiele Ah that's right. After I adjusted the viewbox, I was able to use the FontAwesome SVG icon successfully. Thank you

**Comment by alxshelepenok** [comment]
I'm closing this pull request because the number of icons should not exceed six (#87)

**Comment by AlexanderThiele** [comment]
six is the magic limit of maximum icons we can have? 😅

**Pull request closed without merging**
